/**
 * Core PSD layer type definitions for psd-to-phaser
 *
 * These types represent the JSON structure generated by psd-to-json
 * and used throughout the plugin for type-safe layer processing.
 */

// =============================================================================
// Layer Categories
// =============================================================================

export type LayerCategory = 'sprite' | 'tileset' | 'zone' | 'point' | 'group';

export type SpriteType = 'default' | 'atlas' | 'spritesheet' | 'animation';

// =============================================================================
// Animation Attributes
// =============================================================================

export interface AnimationAttributes {
  frameRate?: number;
  repeat?: number;
  yoyo?: boolean;
  delay?: number;
  repeatDelay?: number;
  duration?: number;
  showOnStart?: boolean;
  hideOnComplete?: boolean;
}

// =============================================================================
// Layer Attributes
// =============================================================================

export interface LayerAttributes extends AnimationAttributes {
  lazyLoad?: boolean;
  [key: string]: unknown;
}

// =============================================================================
// Base Layer Interface
// =============================================================================

export interface BaseLayer {
  name: string;
  category: LayerCategory;
  x: number;
  y: number;
  width: number;
  height: number;
  initialDepth?: number;
  attributes?: LayerAttributes;
  lazyLoad?: boolean;
  hidden?: boolean;
  alpha?: number;
  // Mask properties - applied from layer/group masks in PSD
  mask?: boolean;
  maskPath?: string;
  maskX?: number;
  maskY?: number;
  maskWidth?: number;
  maskHeight?: number;
}

// =============================================================================
// Sprite Layers
// =============================================================================

export interface FrameData {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface SpriteInstance {
  name: string;
  x: number;
  y: number;
}

interface BaseSpriteLayer extends BaseLayer {
  category: 'sprite';
  filePath: string;
}

export interface DefaultSpriteLayer extends BaseSpriteLayer {
  type?: 'default';
  frame?: number;
}

export interface AtlasSpriteLayer extends BaseSpriteLayer {
  type: 'atlas';
  frames: Record<string, FrameData>;
  instances?: SpriteInstance[];
}

export interface SpritesheetLayer extends BaseSpriteLayer {
  type: 'spritesheet';
  frame_width: number;
  frame_height: number;
  frame_count?: number;
  frames: Record<string, FrameData>;
  instances?: SpriteInstance[];
}

export interface AnimationSpriteLayer extends BaseSpriteLayer {
  type: 'animation';
  frame_width: number;
  frame_height: number;
  frame_count?: number;
}

export type SpriteLayer =
  | DefaultSpriteLayer
  | AtlasSpriteLayer
  | SpritesheetLayer
  | AnimationSpriteLayer;

// =============================================================================
// Tileset Layer
// =============================================================================

export interface TilesetLayer extends BaseLayer {
  category: 'tileset';
  columns: number;
  rows: number;
  filetype?: string;
}

// =============================================================================
// Zone Layer
// =============================================================================

export interface ZoneBoundingBox {
  left: number;
  top: number;
  right: number;
  bottom: number;
}

export interface ZoneLayer extends BaseLayer {
  category: 'zone';
  subpaths?: number[][][];
  bbox?: ZoneBoundingBox;
}

// =============================================================================
// Point Layer
// =============================================================================

export interface PointLayer extends BaseLayer {
  category: 'point';
}

// =============================================================================
// Group Layer
// =============================================================================

export interface GroupLayer extends BaseLayer {
  category: 'group';
  children: PsdLayer[];
}

// =============================================================================
// Union Type for All Layers
// =============================================================================

export type PsdLayer =
  | SpriteLayer
  | TilesetLayer
  | ZoneLayer
  | PointLayer
  | GroupLayer;

// =============================================================================
// PSD Document Root
// =============================================================================

export interface PsdDocument {
  width: number;
  height: number;
  tile_slice_size?: number;
  layers: PsdLayer[];
}

// =============================================================================
// Tile Data (for individual tile loading)
// =============================================================================

export interface TileLoadData {
  tilesetName: string;
  col: number;
  row: number;
  filetype?: string;
}

export interface TilePlacementData extends TileLoadData {
  x: number;
  y: number;
  key: string;
  initialDepth?: number;
}

// =============================================================================
// Lazy Load Tile Data (used by camera features)
// =============================================================================

export interface LazyLoadTileData {
  category: 'tile' | 'tileset';
  name: string;
  x: number;
  y: number;
  width: number;
  height: number;
  tile_slice_size: number;
  filetype: string;
  tilesetName: string;
  col: number;
  row: number;
  initialDepth?: number;
  _psdKey?: string;
  loaded?: boolean;
}

// =============================================================================
// Type Guards
// =============================================================================

export function isSpriteLayer(layer: PsdLayer): layer is SpriteLayer {
  return layer.category === 'sprite';
}

export function isTilesetLayer(layer: PsdLayer): layer is TilesetLayer {
  return layer.category === 'tileset';
}

export function isZoneLayer(layer: PsdLayer): layer is ZoneLayer {
  return layer.category === 'zone';
}

export function isPointLayer(layer: PsdLayer): layer is PointLayer {
  return layer.category === 'point';
}

export function isGroupLayer(layer: PsdLayer): layer is GroupLayer {
  return layer.category === 'group' && Array.isArray((layer as GroupLayer).children);
}

export function isAtlasSprite(layer: SpriteLayer): layer is AtlasSpriteLayer {
  return layer.type === 'atlas';
}

export function isSpritesheetSprite(layer: SpriteLayer): layer is SpritesheetLayer {
  return layer.type === 'spritesheet';
}

export function isAnimationSprite(layer: SpriteLayer): layer is AnimationSpriteLayer {
  return layer.type === 'animation';
}

export function isDefaultSprite(layer: SpriteLayer): layer is DefaultSpriteLayer {
  return !layer.type || layer.type === 'default';
}

export function hasMask(layer: PsdLayer): layer is PsdLayer & {
  mask: true;
  maskPath: string;
  maskX: number;
  maskY: number;
  maskWidth: number;
  maskHeight: number;
} {
  return layer.mask === true && typeof layer.maskPath === 'string';
}
