/**
 * Core PSD layer type definitions for psd-to-phaser.
 *
 * These types mirror the JSON structure generated by
 * {@link https://pypi.org/project/psd-to-json/ | psd-to-json} and are used
 * throughout the plugin for type-safe layer processing, loading, and placement.
 *
 * @module types/psd
 */

// =============================================================================
// Layer Categories
// =============================================================================

/** Discriminator for the five layer categories produced by psd-to-json. */
export type LayerCategory = 'sprite' | 'tileset' | 'zone' | 'point' | 'group';

/** Discriminator for sprite sub-types. */
export type SpriteType = 'default' | 'atlas' | 'spritesheet' | 'animation';

// =============================================================================
// Animation Attributes
// =============================================================================

/**
 * Animation properties that can be set via PSD layer naming conventions
 * (e.g. `S | bounce | animation | frameRate: 5, yoyo: true`) or
 * passed as `animationOptions` during `place()`.
 */
export interface AnimationAttributes {
  frameRate?: number;
  repeat?: number;
  yoyo?: boolean;
  delay?: number;
  repeatDelay?: number;
  duration?: number;
  showOnStart?: boolean;
  hideOnComplete?: boolean;
}

// =============================================================================
// Layer Attributes
// =============================================================================

/**
 * Custom key/value pairs parsed from PSD layer names by psd-to-json.
 * Extends animation attributes so animation properties can be set inline.
 */
export interface LayerAttributes extends AnimationAttributes {
  lazyLoad?: boolean;
  [key: string]: unknown;
}

// =============================================================================
// Base Layer Interface
// =============================================================================

/**
 * Properties shared by all layer types in the PSD manifest.
 * Every layer has at minimum a name, category, position, and dimensions.
 */
export interface BaseLayer {
  /** Layer name from the PSD (used as texture key and for path lookups) */
  name: string;
  /** Layer category discriminator */
  category: LayerCategory;
  /** X position in PSD canvas coordinates */
  x: number;
  /** Y position in PSD canvas coordinates */
  y: number;
  /** Width of the layer in pixels */
  width: number;
  /** Height of the layer in pixels */
  height: number;
  /** Depth index for Phaser's display list ordering */
  initialDepth?: number;
  /** Custom attributes parsed from the PSD layer name */
  attributes?: LayerAttributes;
  /** Whether this layer should be deferred for lazy loading */
  lazyLoad?: boolean;
  /** Whether this layer was hidden in the PSD */
  hidden?: boolean;
  /** Opacity of the layer (0–1) */
  alpha?: number;
  /** Whether this layer has an associated mask image */
  mask?: boolean;
  /** Relative path to the mask image file */
  maskPath?: string;
  /** X position of the mask image */
  maskX?: number;
  /** Y position of the mask image */
  maskY?: number;
  /** Width of the mask image */
  maskWidth?: number;
  /** Height of the mask image */
  maskHeight?: number;
}

// =============================================================================
// Sprite Layers
// =============================================================================

/** Position and dimensions of a single frame within a spritesheet or atlas image. */
export interface FrameData {
  x: number;
  y: number;
  width: number;
  height: number;
}

/** A named instance placement for atlas/spritesheet frames. */
export interface SpriteInstance {
  name: string;
  x: number;
  y: number;
}

/** Base interface for all sprite layer sub-types. */
interface BaseSpriteLayer extends BaseLayer {
  category: 'sprite';
  filePath: string;
}

/** A simple single-image sprite (the most common type). */
export interface DefaultSpriteLayer extends BaseSpriteLayer {
  type?: 'default';
  frame?: number;
}

/** A texture atlas with multiple named frames and optional instance placements. */
export interface AtlasSpriteLayer extends BaseSpriteLayer {
  type: 'atlas';
  frames: Record<string, FrameData>;
  instances?: SpriteInstance[];
}

/** A grid-based spritesheet with uniform frame dimensions. */
export interface SpritesheetLayer extends BaseSpriteLayer {
  type: 'spritesheet';
  frame_width: number;
  frame_height: number;
  frame_count?: number;
  frames: Record<string, FrameData>;
  instances?: SpriteInstance[];
}

/** A spritesheet that auto-plays as an animation when placed. */
export interface AnimationSpriteLayer extends BaseSpriteLayer {
  type: 'animation';
  frame_width: number;
  frame_height: number;
  frame_count?: number;
}

/** Union of all sprite layer sub-types. Use type guards to narrow. */
export type SpriteLayer =
  | DefaultSpriteLayer
  | AtlasSpriteLayer
  | SpritesheetLayer
  | AnimationSpriteLayer;

// =============================================================================
// Tileset Layer
// =============================================================================

/**
 * A tileset layer – a large image pre-sliced into a grid of tile images.
 * Tile slices are stored at `tiles/<name>/<sliceSize>/<name>_tile_<col>_<row>.png`.
 */
export interface TilesetLayer extends BaseLayer {
  category: 'tileset';
  columns: number;
  rows: number;
  filetype?: string;
}

// =============================================================================
// Zone Layer
// =============================================================================

/** Axis-aligned bounding box for a zone defined by its edges. */
export interface ZoneBoundingBox {
  left: number;
  top: number;
  right: number;
  bottom: number;
}

/**
 * A zone layer – an invisible area defined by polygon subpaths or a bounding box.
 * Used for hit testing, spawn areas, joystick bounds, `fillZone()`, etc.
 */
export interface ZoneLayer extends BaseLayer {
  category: 'zone';
  subpaths?: number[][][];
  bbox?: ZoneBoundingBox;
}

// =============================================================================
// Point Layer
// =============================================================================

/**
 * A point layer – a single x/y coordinate marker from the PSD.
 * Useful for spawn points, waypoints, or anchors.
 */
export interface PointLayer extends BaseLayer {
  category: 'point';
}

// =============================================================================
// Group Layer
// =============================================================================

/**
 * A group layer – a folder in the PSD that contains child layers.
 * Groups are placed recursively and may carry their own masks.
 */
export interface GroupLayer extends BaseLayer {
  category: 'group';
  children: PsdLayer[];
}

// =============================================================================
// Union Type for All Layers
// =============================================================================

/**
 * Union of all possible layer types in a PSD manifest.
 * Use the type guard functions to narrow to a specific type.
 */
export type PsdLayer =
  | SpriteLayer
  | TilesetLayer
  | ZoneLayer
  | PointLayer
  | GroupLayer;

// =============================================================================
// PSD Document Root
// =============================================================================

/** Root structure of the `data.json` manifest produced by psd-to-json. */
export interface PsdDocument {
  width: number;
  height: number;
  tile_slice_size?: number;
  layers: PsdLayer[];
}

// =============================================================================
// Tile Data (for individual tile loading)
// =============================================================================

/** Data needed to load a single tile slice from disk. */
export interface TileLoadData {
  tilesetName: string;
  col: number;
  row: number;
  filetype?: string;
}

/** Extended tile data that includes placement coordinates and texture key. */
export interface TilePlacementData extends TileLoadData {
  x: number;
  y: number;
  key: string;
  initialDepth?: number;
}

// =============================================================================
// Lazy Load Tile Data (used by camera features)
// =============================================================================

/** Tile data structure used by the lazy-load camera feature. */
export interface LazyLoadTileData {
  category: 'tile' | 'tileset';
  name: string;
  x: number;
  y: number;
  width: number;
  height: number;
  tile_slice_size: number;
  filetype: string;
  tilesetName: string;
  col: number;
  row: number;
  initialDepth?: number;
  _psdKey?: string;
  loaded?: boolean;
}

// =============================================================================
// Type Guards
// =============================================================================

/** Type guard: returns `true` if the layer is any sprite sub-type. */
export function isSpriteLayer(layer: PsdLayer): layer is SpriteLayer {
  return layer.category === 'sprite';
}

/** Type guard: returns `true` if the layer is a tileset. */
export function isTilesetLayer(layer: PsdLayer): layer is TilesetLayer {
  return layer.category === 'tileset';
}

/** Type guard: returns `true` if the layer is a zone. */
export function isZoneLayer(layer: PsdLayer): layer is ZoneLayer {
  return layer.category === 'zone';
}

/** Type guard: returns `true` if the layer is a point. */
export function isPointLayer(layer: PsdLayer): layer is PointLayer {
  return layer.category === 'point';
}

/** Type guard: returns `true` if the layer is a group with children. */
export function isGroupLayer(layer: PsdLayer): layer is GroupLayer {
  return layer.category === 'group' && Array.isArray((layer as GroupLayer).children);
}

/** Type guard: returns `true` if the sprite is an atlas. */
export function isAtlasSprite(layer: SpriteLayer): layer is AtlasSpriteLayer {
  return layer.type === 'atlas';
}

/** Type guard: returns `true` if the sprite is a spritesheet. */
export function isSpritesheetSprite(layer: SpriteLayer): layer is SpritesheetLayer {
  return layer.type === 'spritesheet';
}

/** Type guard: returns `true` if the sprite is an animation. */
export function isAnimationSprite(layer: SpriteLayer): layer is AnimationSpriteLayer {
  return layer.type === 'animation';
}

/** Type guard: returns `true` if the sprite is a default (single-image) sprite. */
export function isDefaultSprite(layer: SpriteLayer): layer is DefaultSpriteLayer {
  return !layer.type || layer.type === 'default';
}

/** Type guard: returns `true` if the layer has a mask defined (with all required mask properties). */
export function hasMask(layer: PsdLayer): layer is PsdLayer & {
  mask: true;
  maskPath: string;
  maskX: number;
  maskY: number;
  maskWidth: number;
  maskHeight: number;
} {
  return layer.mask === true && typeof layer.maskPath === 'string';
}
