/**
 * Load module – responsible for fetching PSD JSON manifests and queuing
 * all referenced assets (sprites, tiles, atlases, masks) with Phaser's loader.
 *
 * @module load
 */

import PsdToPhaserPlugin from '../../PsdToPhaser';
import { processJSON } from './processJSON';
import { loadMultiple } from './loadMultiple';

import type { LoadOptions, MultiplePsdConfig, PsdDocument } from '../../types';

export type { LoadOptions };

/**
 * Factory that creates the public `load` / `loadMultiple` API bound to the plugin.
 *
 * @param plugin - The PsdToPhaser plugin instance
 * @returns An object with `load()` and `loadMultiple()` methods
 *
 * @internal
 */
export default function loadModule(plugin: PsdToPhaserPlugin) {
  return {
    /**
     * Load a single PSD manifest and its assets.
     *
     * Fetches `<psdFolderPath>/data.json`, categorises layers into initial
     * and lazy-load buckets, then queues all initial-load assets with Phaser's
     * loader. Emits `psdLoadProgress` and `psdLoadComplete` events on the scene.
     *
     * @param scene - The Phaser scene whose loader will queue the assets
     * @param key - A unique key to identify this PSD (used later in `place()`, `getData()`, etc.)
     * @param psdFolderPath - Path to the folder generated by psd-to-json
     * @param options - Optional load configuration (e.g. `{ lazyLoad: true }`)
     *
     * @example
     * ```js
     * // Basic load
     * this.P2P.load(this, "psd_key", "assets/simple");
     *
     * // Lazy-load all layers
     * this.P2P.load(this, "psd_key", "assets/simple", { lazyLoad: true });
     *
     * // Lazy-load specific layers only
     * this.P2P.load(this, "psd_key", "assets/simple", {
     *   lazyLoad: ["background", "monster"]
     * });
     * ```
     */
    load(scene: Phaser.Scene, key: string, psdFolderPath: string, options?: LoadOptions): void {
      const jsonPath = `${psdFolderPath}/data.json`;

      scene.load.json(key, jsonPath);

      scene.load.once(`filecomplete-json-${key}`, (_key: string, _type: string, data: PsdDocument) => {
        if (data) {
          processJSON(scene, key, data, psdFolderPath, plugin, options);
        } else {
          console.error(`Loaded JSON is empty or invalid for key: ${key}`);
        }
      });

      scene.load.once('loaderror', (file: Phaser.Loader.File) => {
        if (file.key === key) {
          console.error(`Failed to load JSON file: ${jsonPath}`);
        }
      });

      if (!scene.load.isLoading()) {
        scene.load.start();
      }
    },
    /**
     * Load multiple PSDs at once, each with an independent position offset.
     *
     * Coordinates progress tracking across all PSDs and emits a single set
     * of `psdLoadProgress` / `psdLoadComplete` events for the combined load.
     *
     * @param scene - The Phaser scene whose loader will queue the assets
     * @param configs - Array of PSD configurations, each with key, path, position, and optional lazyLoad
     *
     * @example
     * ```js
     * this.P2P.loadMultiple(this, [
     *   { key: "bg", path: "assets/background", position: { x: 0, y: 0 } },
     *   { key: "fg", path: "assets/foreground", position: { x: 100, y: 50 } },
     * ]);
     * ```
     */
    loadMultiple: loadMultiple(plugin) as (scene: Phaser.Scene, configs: MultiplePsdConfig[]) => void
  };
}